### ISSUE TITLE
Windows 7 not supported

### ISSUE THREAD

**Issue by brynts** [aspenluxxxy/xenon#10]
please add Windows 7 support

`The procedure entry point CoIncrementMTAUsage could not be located in the dynamic link library ole32.dll`

CoIncrementMTAUsage not work on Windows 7

[Screenshot](https://i.ibb.co/2K5Ypdm/Untitled.png)

**Comment by italoboy** [comment]
I have this issue and just purchased Xenon, what should i do?

**Comment by aspenluxxxy** [comment]
@brynts @italoboy Just email your Chariz purchase ID to support@aspenuwu.me for a refund.

I have no plans to try to get this working on an EOL 12-year-old OS.
