### ISSUE TITLE
Xenon Not Showing Up in My File Explorer

### ISSUE THREAD

**Issue by direpromise** [aspenluxxxy/xenon#12]
## Describe the bug
The first day I paired it, it gave me the notification that it successfully paired, but it just wont show up in my file explorer

Also I tried manually mapping the webdav drive but that would just not work

And yes my firewall was down.

## To Reproduce
1. Go to Xenon
2. Click on Pair Device/Manually pair device

## Expected behavior
Xenon not showing in my file explorer

## Screenshots
https://paste.ee/p/s2NJM

## Setup (please complete the following information):
 - **iOS Version**: 14.3
 - **Jailbreak used**: Unc0ver
 - **Computer OS**: Windows 10

**Comment by aspenluxxxy** [comment]
> Also I tried manually mapping the webdav drive but that would just not work

That's weird, log shows that it successfully connected, it just failed to map it for whatever reason?

```
23:08:21 [INFO] succesfully connected to 192.168.77.116, bringing up webserver
```

Try seeing if you can connect to it via Filezilla or WinSCP?

**Comment by direpromise** [comment]
I did connect my phone via WinSCP before trying Xenon, WinSCP worked just fine for me, sorry for the late reply

**Comment by aspenluxxxy** [comment]
I mean connecting to the Xenon localhost server at `localhost:4200` with WinSCP while it's connected. Trying to figure out if it's an Explorer problem.

**Comment by direpromise** [comment]
> I mean connecting to the Xenon localhost server at `localhost:4200` with WinSCP (use the WebDAV connection method, no username/password) while it's connected. Trying to figure out if it's an Explorer problem.

I just tried that, it worked

**Comment by direpromise** [comment]
My issue still remains

**Comment by aspenluxxxy** [comment]
It's not showing up at all, no localhost/davwwwhost at all, right?

**Comment by direpromise** [comment]
> It's not showing up at all, no localhost/davwwwhost at all, right?

Yes
