### ISSUE TITLE
Immediate error after every connection attempt

### ISSUE THREAD

**Issue by joekenda404** [aspenluxxxy/xenon#13]
## Describe the bug
This applies to the current version and the previous 2 versions of the client and server - never had a successful connection.
Log reflects web server starting, latest version check, "successful connection" and "bringing up webserver" - followed by:

[ERROR] thread 'tokio-runtime-worker' panicked at 'error binding to 127.0.0.1:4200: error creating server listener: Can't assign requested address (os error 49)': /Users/aspen/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.4/src/server/server.rs:67

## To Reproduce
1. Go to Settings > Xenon
2. Click on Pair Computer
3. Scan QR code
4. See error above

## Expected behavior
Connect to/browse device

## Setup (please complete the following information):
 - **OS: 14.4 (iPhone X), iPadOs 14.2:
 - **Jailbreak used**:  checkra1n
 - **Computer OS**: MacOS Mojave

**Comment by aspenluxxxy** [comment]
Is anything else listening on port 4200?

**Comment by joekenda404** [comment]
Nope, checked using net stat and lsof

**Comment by aspenluxxxy** [comment]
did you try changing the port in the config.toml?

This is the first time i've seen that happen, weird.

**Comment by joekenda404** [comment]
Just tried changing config.toml to various ports, restarting the server each time. Same error with both devices (?)

**Comment by joekenda404** [comment]
Also tried flushing routing table (on mac), regenerating keys (on iPhone) and copy/pasting manual configuration. Same error.

**Comment by joekenda404** [comment]
Also, I can ping Mac from phone and phone from mac using the ports from the config.toml - but still get same behavior/error.

**Comment by aspenluxxxy** [comment]
If you're curious, this is the line of code that panics: https://github.com/hyperium/hyper/blob/master/src/server/server.rs#L65-L70

I'm still clueless as to what's causing it tho. Maybe this just means that I should skip the scuffed WebDAV proxy and go full FUSE?

**Comment by joekenda404** [comment]
Thanks, I'm going to try it with another Mac tonight and see if the same thing happens.

**Comment by joekenda404** [comment]
It works with my M1 Mac Mini (running Big Sur). The difference seems to be that, while installing the Xenon client on that Mac, I am prompted to allow permission for the client to control Finder. After granting permission, Xenon appears under System Preferences > Security and Privacy > Automation > Finder.

On my MacBook Pro running Mojave, this permission request is never made while installing the client and cannot be added manually (it must be requested by the app). 

Is there any reason why the client might not request this permission when installing on Mojave?

Thanks.

**Comment by aspenluxxxy** [comment]
No clue. It runs an embedded AppleScript file, which is what asks for permission. It does the same thing as Go -> Connect To Server, but automatic.

**Comment by joekenda404** [comment]
That IS weird, then. I'm stumped.
