### ISSUE TITLE
Mine is not working can’t even scan the barcode because it’s not clicking

### ISSUE THREAD

**Issue by oluwabrown** [aspenluxxxy/xenon#15]
## Setup (please complete the following information):
 - **iOS Version**:
 - **Jailbreak used**:
 - **Computer OS**:

**Comment by junior2377** [comment]
Clicked settings
Clicked xenon
Clicked “pair computer”
Nothing happens. Can’t scan computer to pair.

**Comment by aspenluxxxy** [comment]
Have y'all tried manually configuring it?

**Comment by kafeidoudoumao** [comment]
I can't turn on my camera either

**Comment by aspenluxxxy** [comment]
oh huh, this is actually a bug. i'm looking into it

**Comment by aspenluxxxy** [comment]
bug will be fixed in Xenon 1.1.3, which should release tomorrow-ish morning
