### ISSUE TITLE
[Question/Feature Request] Multi-Device Support

### ISSUE THREAD

**Issue by hnlkaitan** [aspenluxxxy/xenon#18]
## Description
Was wondering if there was any way that I could have multiple devices connected at the same time? Like having both of the `[connection]` in `config.toml`? Or is there some sort of workaround I could use, maybe like mounting my other device(s) through `ssh` on the "host" iOS/iPadOS device?

## Expected behavior
Have multiple mount points, from each device.

## Setup (please complete the following information):
 - **iOS Version**: iOS 14.3
 - **Jailbreak used**: unc0ver 6.1.2
 - **Computer OS**: macOS Big Sur 11.2.3 (Apple Silicon)

**Comment by aspenluxxxy** [comment]
This functionality is not implemented, sorry.
