### ISSUE TITLE
Why can't rename or delete already created mounts?

### ISSUE THREAD

**Issue by Azadss** [aspenluxxxy/xenon#21]
Is it possible to rename and delete the mounts we have created? I know its not a bug but its a really big missing feature imo. I hope you can add it aspen thanks.

**Comment by aspenluxxxy** [comment]
Renaming them isn't implemented, but you **can** swipe-to-delete them (and if you want to rename, just delete then re-create)

**Comment by Azadss** [comment]
> Renaming them isn't implemented, but you **can** swipe-to-delete them (and if you want to rename, just delete then re-create)

Uh I wasn’t be able to delete while I was writing this issue post but I think there was a glitch exist at that moment, now I can delete thank you for quick responding.
